exclude: >
  (?x)^(
      .+/airflow_override/.+|
      .+/_vendor/.+|
      .+/_vendor_package/.+|
  )$
repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.6
        files: \.pyi?$
        exclude: dbnd/_vendor
        # support running black from parent dirrectory and from dbnd-core root:
        entry: sh -c 'black --config dbnd-core/pyproject.toml $@ || black $@'

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--resolve-all-configs]
        language_version: python3.6

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=3000' ]
      - id: trailing-whitespace
