exclude: >
  (?x)^(
      .+/airflow_override/.+|
      .+/_vendor/.+|
      .+/_vendor_package/.+|
  )$
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.6
        files: \.pyi?$
        exclude: dbnd/_vendor
        # override until resolved: https://github.com/psf/black/issues/402
        types: []

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-path setup.cfg]
        language_version: python3.6
